# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Leonard
email: null
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: "leonard, actor, anorak, artist, athlete"
skills: "Analysing schematics... ðŸš§" # "Actor, Anorak, Artist, & Athlete"
meta_author: Leonard Sheng Sheng Lee

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leonardlee.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sheeeng
github_username: sheeeng

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Build settings
markdown: kramdown
permalink: pretty
# theme: freelancer-theme-jekyll  # Custom theme - using layouts directly
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-data # Not supported by GitHub Pages
  - jemoji

# Freelancer Theme Settings
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Leonard Lee
  location: Location
  social: In The Matrix
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # keep-sorted start
  - title: github
    url: http://github.com/sheeeng
  - title: instagram
    url: https://www.instagram.com/leeonarding
  - title: linkedin
    url: http://www.linkedin.com/in/sheeeng
  - title: mastodon
    url: https://hachyderm.io/@leonard
  - title: twitter
    url: https://bsky.app/profile/sheeeng.bsky.social
  # keep-sorted end

# Postal address (add as many lines as necessary)
address:
  - line: Oslo
  - line: Norway

# Credits content
credits: 'Freelancer is a free to use, open source theme created by <a href="https://github.com/jeromelachaud/freelancer-theme">Jerome Lachaud</a>.'

# For posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .direnv
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - flake.nix
  - flake.lock
